//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4338Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class isrpo_2_lbEntities : DbContext
    {
        private static isrpo_2_lbEntities _context;
		public isrpo_2_lbEntities()
            : base("name=isrpo_2_lbEntities")
        {
        }
		public static isrpo_2_lbEntities GetContext()
		{
			if (_context == null)
				_context = new isrpo_2_lbEntities();
			return _context;
		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usl> Usl { get; set; }
    }
}
